services:
  postgres:
    image: postgres:16-alpine
    container_name: wasi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-wasi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wasi_password}
      POSTGRES_DB: ${POSTGRES_DB:-wasi_peru}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-wasi} -d ${POSTGRES_DB:-wasi_peru}']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: wasi_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://${POSTGRES_USER:-wasi}:${POSTGRES_PASSWORD:-wasi_password}@postgres:5432/${POSTGRES_DB:-wasi_peru}?schema=public
      FRONTEND_URL: http://localhost:3000
      BACKEND_URL: http://localhost:4000
      CORS_ORIGINS: http://localhost:3000
      JWT_SECRET: ${JWT_SECRET:-desarrollo-secreto-largo-cambiar-en-produccion}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-desarrollo-refresh-secreto-cambiar-produccion}
      STORAGE_DRIVER: local
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: wasi_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
      API_INTERNAL_URL: http://backend:4000/api/v1
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:
  backend_uploads:
