/** Único lugar donde se declaran las rutas de la API. */
export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  users: {
    root: '/users',
    me: '/users/me',
    stats: '/users/me/stats',
    byId: (id: string) => `/users/${id}`,
    role: (id: string) => `/users/${id}/role`,
    activate: (id: string) => `/users/${id}/activate`,
    deactivate: (id: string) => `/users/${id}/deactivate`,
  },
  properties: {
    root: '/properties',
    mine: '/properties/mine',
    featured: '/properties/featured',
    bySlug: (slug: string) => `/properties/slug/${slug}`,
    similar: (slug: string) => `/properties/slug/${slug}/similar`,
    byId: (id: string) => `/properties/${id}`,
    status: (id: string, status: string) => `/properties/${id}/status/${status}`,
    featuredToggle: (id: string, value: boolean) => `/properties/${id}/featured/${value}`,
  },
  categories: { root: '/categories', admin: '/categories/admin/all', byId: (id: number) => `/categories/${id}` },
  amenities: { root: '/amenities', grouped: '/amenities/grouped', byId: (id: number) => `/amenities/${id}` },
  locations: {
    departments: '/locations/departments',
    top: '/locations/departments/top',
    provinces: (id: number) => `/locations/departments/${id}/provinces`,
    districts: (id: number) => `/locations/provinces/${id}/districts`,
  },
  availability: {
    occupied: (id: string) => `/availability/properties/${id}/occupied`,
    check: (id: string) => `/availability/properties/${id}/check`,
    blocks: (id: string) => `/availability/properties/${id}/blocks`,
    block: (id: string) => `/availability/blocks/${id}`,
  },
  reservations: {
    root: '/reservations',
    mine: '/reservations/me',
    byId: (id: string) => `/reservations/${id}`,
    status: (id: string) => `/reservations/${id}/status`,
    cancel: (id: string) => `/reservations/${id}/cancel`,
  },
  reviews: {
    root: '/reviews',
    mine: '/reviews/me',
    byProperty: (id: string) => `/reviews/property/${id}`,
    summary: (id: string) => `/reviews/property/${id}/summary`,
    byId: (id: string) => `/reviews/${id}`,
  },
  favorites: { root: '/favorites', ids: '/favorites/ids', toggle: (id: string) => `/favorites/${id}/toggle` },
  uploads: {
    propertyImages: (id: string) => `/uploads/properties/${id}/images`,
    reorder: (id: string) => `/uploads/properties/${id}/images/reorder`,
    main: (id: string) => `/uploads/images/${id}/main`,
    image: (id: string) => `/uploads/images/${id}`,
    avatar: '/uploads/avatar',
  },
  whatsapp: { property: (id: string) => `/whatsapp/properties/${id}/link`, support: '/whatsapp/support' },
  admin: {
    dashboard: '/admin/dashboard',
    reservationsSeries: '/admin/dashboard/reservations-series',
    usersSeries: '/admin/dashboard/users-series',
    topProperties: '/admin/dashboard/top-properties',
    propertyPerformance: '/admin/dashboard/property-performance',
    channelSeries: '/admin/dashboard/channel-series',
    recent: '/admin/dashboard/recent-reservations',
    calendar: '/admin/calendar',
    calendarExport: '/admin/calendar/export',
    calendarImport: '/admin/calendar/import',
    calendarEntries: '/admin/calendar/entries',
    calendarEntry: (id: string) => `/admin/calendar/entries/${id}`,

    // Anfitriones
    hostApplications: '/admin/hosts/applications',
    hostApplication: (id: string) => `/admin/hosts/applications/${id}`,
    hostApplicationDocuments: (id: string) => `/admin/hosts/applications/${id}/documents`,
    hostApplicationAccessLog: (id: string) => `/admin/hosts/applications/${id}/access-log`,
    hostApplicationReview: (id: string) => `/admin/hosts/applications/${id}/review`,
    hosts: '/admin/hosts',
    hostSuspend: (id: string) => `/admin/hosts/${id}/suspend`,
    hostReactivate: (id: string) => `/admin/hosts/${id}/reactivate`,

    // Planes y pagos
    hostPayments: '/admin/hosts/payments',
    hostPaymentReview: (id: string) => `/admin/hosts/payments/${id}/review`,
    hostPaymentCash: '/admin/hosts/payments/cash',
  },

  hosts: {
    me: '/hosts/me',
    applications: '/hosts/applications',
    myProfile: '/hosts/me/profile',
    reservations: '/reservations/host',
    plans: '/hosts/plans',
    subscription: '/hosts/subscription',
    subscriptionPayment: (id: string) => `/hosts/subscription/${id}/payment`,
    subscriptionCancel: (id: string) => `/hosts/subscription/${id}/cancel`,
    freeSlot: '/hosts/subscription/free-slot',
    byId: (id: string) => `/hosts/profile/${id}`,
  },
} as const;
